# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20170107_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_description',
            field=models.CharField(default='SOME STRING', max_length=10000),
        ),
    ]
