# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='kitchen',
            field=models.CharField(default='e.g. Italian', max_length=250),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.CharField(default='What to do?', max_length=10000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_title',
            field=models.CharField(default='e.g. Lasagna', max_length=500),
        ),
    ]
