# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20170108_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(default='e.g. Main Dish', max_length=500),
        ),
    ]
