# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient_1',
            field=models.CharField(default='', max_length=500),
        ),
    ]
