# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20170108_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_3',
            field=models.CharField(default='', max_length=500),
        ),
    ]
